name: CI
on:
  push:
  release:
    types:
      - created
jobs:
  test:
    name: Test on Node 14 using ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps and test (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
  publish:
    name: Generate changelog and publish to NPM
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up git credentials
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Configure node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Generate changelog & tag commit
        run: yarn release

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: Push changes to repository
        run: |
          git push
